type StateType = {
  state: string;
  abv: string;
};

export const states: StateType[] = [
  { state: "Alaska", abv: "AK" },
  { state: "Alabama", abv: "AL" },
  { state: "Arkansas", abv: "AR" },
  { state: "Arizona", abv: "AZ" },
  { state: "California", abv: "CA" },
  { state: "Colorado", abv: "CO" },
  { state: "Connecticut", abv: "CT" },
  { state: "Delaware", abv: "DE" },
  { state: "Florida", abv: "FL" },
  { state: "Georgia", abv: "GA" },
  { state: "Hawaii", abv: "HI" },
  { state: "Iowa", abv: "IA" },
  { state: "Idaho", abv: "ID" },
  { state: "Illinois", abv: "IL" },
  { state: "Indiana", abv: "IN" },
  { state: "Kansas", abv: "KS" },
  { state: "Kentucky", abv: "KY" },
  { state: "Louisiana", abv: "LA" },
  { state: "Massachusetts", abv: "MA" },
  { state: "Maryland", abv: "MD" },
  { state: "Maine", abv: "ME" },
  { state: "Michigan", abv: "MI" },
  { state: "Minnesota", abv: "MN" },
  { state: "Missouri", abv: "MO" },
  { state: "Mississippi", abv: "MS" },
  { state: "Montana", abv: "MT" },
  { state: "North Carolina", abv: "NC" },
  { state: "North Dakota", abv: "ND" },
  { state: "Nebraska", abv: "NE" },
  { state: "New Hampshire", abv: "NH" },
  { state: "New Jersey", abv: "NJ" },
  { state: "New Mexico", abv: "NM" },
  { state: "Nevada", abv: "NV" },
  { state: "New York", abv: "NY" },
  { state: "Ohio", abv: "OH" },
  { state: "Oklahoma", abv: "OK" },
  { state: "Oregon", abv: "OR" },
  { state: "Pennsylvania", abv: "PA" },
  { state: "Rhode Island", abv: "RI" },
  { state: "South Carolina", abv: "SC" },
  { state: "South Dakota", abv: "SD" },
  { state: "Tennessee", abv: "TN" },
  { state: "Texas", abv: "TX" },
  { state: "Utah", abv: "UT" },
  { state: "Virginia", abv: "VA" },
  { state: "Vermont", abv: "VT" },
  { state: "Washington", abv: "WA" },
  { state: "Wisconsin", abv: "WI" },
  { state: "West Virginia", abv: "WV" },
  { state: "Wyoming", abv: "WY" },
];
