type TimeZoneType = {
  value: string;
  text: string;
};

export const timeZones: TimeZoneType[] = [
  { value: "US/Alaska", text: "Alaska" },
  { value: "US/Central", text: "Central" },
  { value: "US/Eastern", text: "Eastern" },
  { value: "US/Hawaii", text: "Hawaii" },
  { value: "US/Mountain", text: "Mountain" },
  { value: "US/Pacific", text: "Pacific" },
];

type StateType = {
  state: string;
  abv: string;
  offset: number;
  offTime: string;
  zone: string;
  website:string;
};

export const states: StateType[] = [
  {
    state: "Alabama",
    abv: "AL",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "Alaska",
    abv: "AK",
    offset: -9,
    offTime: "UTC−09:00 AKT",
    zone: "US/Alaska",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "Arizona",
    abv: "AZ",
    offset: -7,
    offTime: "UTC−07:00 MT",
    zone: "US/Mountain",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "Arkansas",
    abv: "AR",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "California",
    abv: "CA",
    offset: -8,
    offTime: "UTC−08:00 PT",
    zone: "US/Pacific",
    website:"https://cdicloud.insurance.ca.gov/cal/IndividualNameSearch",
  },
  {
    state: "Colorado",
    abv: "CO",
    offset: -7,
    offTime: "UTC−07:00 ET",
    zone: "US/Mountain",
    website:"https://www.sircon.com/ComplianceExpress/Inquiry/consumerInquiry.do",
  },
  {
    state: "Connecticut",
    abv: "CT",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "Delaware",
    abv: "DE",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "Florida",
    abv: "FL",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
    website:"",
  },
  {
    state: "Georgia",
    abv: "GA",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
    website:"https://licenseesearch.fldfs.com/",
  },
  {
    state: "Hawaii",
    abv: "HI",
    offset: -10,
    offTime: "UTC−10:00 HT",
    zone: "US/Hawaii",
    website:"https://www.sircon.com/landingPages/states/georgia/content.jsp",
  },
  {
    state: "Iowa",
    abv: "IA",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
    website:"https://insurance.ehawaii.gov/hils/",
  },
  {
    state: "Idaho",
    abv: "ID",
    offset: -7,
    offTime: "UTC−07:00 ET",
    zone: "US/Mountain",
    website:"https://apps.doi.idaho.gov/main/PublicForms/LicenseSearch?pn=1&amp;ps=100&amp;sc=0&amp;sd=0&amp;apn=1&amp;aps=100&amp;asc=1&amp;asd=1&amp;fc=1&amp;fv=grady+polcyn&amp;zip=&amp;it=0&amp;st=0",
  },
  {
    state: "Illinois",
    abv: "IL",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "Indiana",
    abv: "IN",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
    website:"https://www.sircon.com/ComplianceExpress/Inquiry/consumerInquiry.do",
  },
  {
    state: "Iowa",
    abv: "IA",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "Kansas",
    abv: "KS",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "Kentucky",
    abv: "KY",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
    website:"https://insurance.ky.gov/ppc/Agent/Default.aspx",
  },
  {
    state: "Louisiana",
    abv: "LA",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
    website:"https://www.ldi.la.gov/onlineservices/ProducerAdjusterSearch/",
  },
  {
    state: "Maine",
    abv: "ME",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
    website:"https://www.maine.gov/pfr/insurance/licensee-search",
  },
  {
    state: "Maryland",
    abv: "MD",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "Massachusetts",
    abv: "MA",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "Michigan",
    abv: "MI",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
    website:"https://difs.state.mi.us/locators?searchtype=InsAgent",
  },
  {
    state: "Minnesota",
    abv: "MN",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
    website:"https://www.sircon.com/ComplianceExpress/Inquiry/consumerInquiry.do",
  },
  {
    state: "Mississippi",
    abv: "MS",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
    website:"https://www.mid.ms.gov/licensing-search/individual-entity-search.aspx",
  },
  {
    state: "Missouri",
    abv: "MO",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "Montana",
    abv: "MT",
    offset: -7,
    offTime: "UTC−07:00 ET",
    zone: "US/Mountain",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "Nebraska",
    abv: "NE",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "Nevada",
    abv: "NV",
    offset: -7,
    offTime: "UTC−07:00 ET",
    zone: "US/Mountain",
    website:"https://www.sircon.com/ComplianceExpress/Inquiry/consumerInquiry.do",
  },
  {
    state: "New Hampshire",
    abv: "NH",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "New Jersey",
    abv: "NJ",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "New Mexico",
    abv: "NM",
    offset: -7,
    offTime: "UTC−07:00 ET",
    zone: "US/Mountain",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "New York",
    abv: "NY",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
    website:"https://myportal.dfs.ny.gov/nylinxext/elsearch.alice",
  },
  {
    state: "North Carolina",
    abv: "NC",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "North Dakota",
    abv: "ND",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "Ohio",
    abv: "OH",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
    website:"https://gateway.insurance.ohio.gov/UI/ODI.Agent.Public.UI/AgentSearch.mvc/DisplaySearch",
  },
  {
    state: "Oklahoma",
    abv: "OK",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "Oregon",
    abv: "OR",
    offset: -7,
    offTime: "UTC−07:00 ET",
    zone: "US/Mountain",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "Pennsylvania",
    abv: "PA",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
    website:"https://apps02.ins.pa.gov/producer/ilist1.asp",
  },
  {
    state: "Rhode Island",
    abv: "RI",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "South Carolina",
    abv: "SC",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "South Dakota",
    abv: "SD",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
    website:"https://www.sircon.com/ComplianceExpress/Inquiry/consumerInquiry.do",
  },
  {
    state: "Tennessee",
    abv: "TN",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "Texas",
    abv: "TX",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
    website:"https://txapps.texas.gov/NASApp/tdi/TdiARManager",
  },
  {
    state: "Utah",
    abv: "UT",
    offset: -7,
    offTime: "UTC−07:00 ET",
    zone: "US/Mountain",
    website:"https://www.sircon.com/ComplianceExpress/Inquiry/consumerInquiry.do",
  },
  {
    state: "Vermont",
    abv: "VT",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "Virginia",
    abv: "VA",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
    website:"https://scc.virginia.gov/boi/ConsumerInquiry/Search.aspx?searchType=agent",
  },
  {
    state: "Washington",
    abv: "WA",
    offset: -8,
    offTime: "UTC−08:00 PT",
    zone: "US/Pacific",
    website:"https://fortress.wa.gov/oic/consumertoolkit/Search.aspx",
  },
  {
    state: "West Virginia",
    abv: "WV",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "Wisconsin",
    abv: "WI",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
    website:"https://sbs.naic.org/solar-external-lookup/",
  },
  {
    state: "Wyoming",
    abv: "WY",
    offset: -7,
    offTime: "UTC−07:00 ET",
    zone: "US/Mountain",
    website:"https://www.sircon.com/ComplianceExpress/Inquiry/consumerInquiry.do",
  },
];
