type TimeZoneType = {
  value: string;
  text: string;
};

export const timeZones: TimeZoneType[] = [
  { value: "US/Alaska", text: "Alaska" },
  { value: "US/Central", text: "Central" },
  { value: "US/Eastern", text: "Eastern" },
  { value: "US/Hawaii", text: "Hawaii" },
  { value: "US/Mountain", text: "Mountain" },
  { value: "US/Pacific", text: "Pacific" },
];

type StateType = {
  state: string;
  abv: string;
  offset: number;
  offTime: string;
  zone: string;
};

export const states: StateType[] = [
  {
    state: "Alabama",
    abv: "AL",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
  },
  {
    state: "Alaska",
    abv: "AK",
    offset: -9,
    offTime: "UTC−09:00 AKT",
    zone: "US/Alaska",
  },
  {
    state: "Arizona",
    abv: "AZ",
    offset: -7,
    offTime: "UTC−07:00 MT",
    zone: "US/Mountain",
  },
  {
    state: "Arkansas",
    abv: "AR",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
  },
  {
    state: "California",
    abv: "CA",
    offset: -8,
    offTime: "UTC−08:00 PT",
    zone: "US/Pacific",
  },
  {
    state: "Colorado",
    abv: "CO",
    offset: -7,
    offTime: "UTC−07:00 ET",
    zone: "US/Mountain",
  },
  {
    state: "Connecticut",
    abv: "CT",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
  },
  {
    state: "Delaware",
    abv: "DE",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
  },
  {
    state: "Florida",
    abv: "FL",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
  },
  {
    state: "Georgia",
    abv: "GA",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
  },
  {
    state: "Hawaii",
    abv: "HI",
    offset: -10,
    offTime: "UTC−10:00 HT",
    zone: "US/Hawaii",
  },
  {
    state: "Iowa",
    abv: "IA",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
  },
  {
    state: "Idaho",
    abv: "ID",
    offset: -7,
    offTime: "UTC−07:00 ET",
    zone: "US/Mountain",
  },
  {
    state: "Illinois",
    abv: "IL",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
  },
  {
    state: "Indiana",
    abv: "IN",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
  },

  {
    state: "Kansas",
    abv: "KS",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
  },
  {
    state: "Kentucky",
    abv: "KY",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
  },
  {
    state: "Louisiana",
    abv: "LA",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
  },
  {
    state: "Maine",
    abv: "ME",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
  },
  {
    state: "Maryland",
    abv: "MD",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
  },
  {
    state: "Massachusetts",
    abv: "MA",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
  },
  {
    state: "Michigan",
    abv: "MI",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
  },
  {
    state: "Minnesota",
    abv: "MN",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
  },
  {
    state: "Missouri",
    abv: "MO",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
  },
  {
    state: "Mississippi",
    abv: "MS",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
  },
  {
    state: "Montana",
    abv: "MT",
    offset: -7,
    offTime: "UTC−07:00 ET",
    zone: "US/Mountain",
  },
  {
    state: "Nebraska",
    abv: "NE",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
  },
  {
    state: "Nevada",
    abv: "NV",
    offset: -7,
    offTime: "UTC−07:00 ET",
    zone: "US/Mountain",
  },
  {
    state: "New Hampshire",
    abv: "NH",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
  },
  {
    state: "New Jersey",
    abv: "NJ",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
  },
  {
    state: "New Mexico",
    abv: "NM",
    offset: -7,
    offTime: "UTC−07:00 ET",
    zone: "US/Mountain",
  },
  {
    state: "New York",
    abv: "NY",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
  },
  {
    state: "North Carolina",
    abv: "NC",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
  },
  {
    state: "North Dakota",
    abv: "ND",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
  },
  {
    state: "Ohio",
    abv: "OH",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
  },
  {
    state: "Oklahoma",
    abv: "OK",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
  },
  {
    state: "Oregon",
    abv: "OR",
    offset: -7,
    offTime: "UTC−07:00 ET",
    zone: "US/Mountain",
  },
  {
    state: "Pennsylvania",
    abv: "PA",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
  },
  {
    state: "Rhode Island",
    abv: "RI",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
  },
  {
    state: "South Carolina",
    abv: "SC",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
  },
  {
    state: "South Dakota",
    abv: "SD",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
  },
  {
    state: "Tennessee",
    abv: "TN",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
  },
  {
    state: "Texas",
    abv: "TX",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
  },
  {
    state: "Utah",
    abv: "UT",
    offset: -7,
    offTime: "UTC−07:00 ET",
    zone: "US/Mountain",
  },
  {
    state: "Vermont",
    abv: "VT",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
  },
  {
    state: "Virginia",
    abv: "VA",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
  },
  {
    state: "Washington",
    abv: "WA",
    offset: -8,
    offTime: "UTC−08:00 PT",
    zone: "US/Pacific",
  },
  {
    state: "West Virginia",
    abv: "WV",
    offset: -5,
    offTime: "UTC−05:00 ET",
    zone: "US/Eastern",
  },
  {
    state: "Wisconsin",
    abv: "WI",
    offset: -6,
    offTime: "UTC−06:00 CT",
    zone: "US/Central",
  },
  {
    state: "Wyoming",
    abv: "WY",
    offset: -7,
    offTime: "UTC−07:00 ET",
    zone: "US/Mountain",
  },
];
