type StateType = {
  state: string;
  abv: string;
  offset:number;
  offTime:string
};

export const states: StateType[] = [
  { state: "Alabama", abv: "AL",offset:-6,offTime:"UTC−06:00 CT"},
  { state: "Alaska", abv: "AK" ,offset:-9,offTime:"UTC−09:00 AKT"},
  { state: "Arizona", abv: "AZ" ,offset:-7,offTime:"UTC−07:00 MT"},
  { state: "Arkansas", abv: "AR" ,offset:-6,offTime:"UTC−06:00 CT"},
  { state: "California", abv: "CA" ,offset:-8,offTime:"UTC−08:00 PT"},
  { state: "Colorado", abv: "CO" ,offset:-7,offTime:"UTC−07:00 MT"},
  { state: "Connecticut", abv: "CT" ,offset:-5,offTime:"UTC−05:00 ET"},
  { state: "Delaware", abv: "DE" ,offset:-5,offTime:"UTC−05:00 ET"},
  { state: "Florida", abv: "FL" ,offset:-5,offTime:"UTC−05:00 ET"},
  { state: "Georgia", abv: "GA" ,offset:-5,offTime:"UTC−05:00 ET"},
  { state: "Hawaii", abv: "HI" ,offset:-10,offTime:"UTC−10:00 HT"},
  { state: "Iowa", abv: "IA" ,offset:-6,offTime:"UTC−06:00 CT"},
  { state: "Idaho", abv: "ID" ,offset:-7,offTime:"UTC−07:00 MT"},
  { state: "Illinois", abv: "IL" ,offset:-6,offTime:"UTC−06:00 CT"},
  { state: "Indiana", abv: "IN" ,offset:-5,offTime:"UTC−05:00 ET"},

  { state: "Kansas", abv: "KS" ,offset:-6,offTime:"UTC−06:00 CT"},
  { state: "Kentucky", abv: "KY" ,offset:-5,offTime:"UTC−05:00 ET"},
  { state: "Louisiana", abv: "LA" ,offset:-6,offTime:"UTC−06:00 CT"},
  { state: "Maine", abv: "ME" ,offset:-5,offTime:"UTC−05:00 ET"},
  { state: "Maryland", abv: "MD" ,offset:-5,offTime:"UTC−05:00 ET"},
  { state: "Massachusetts", abv: "MA" ,offset:-5,offTime:"UTC−05:00 ET"},
  { state: "Michigan", abv: "MI" ,offset:-5,offTime:"UTC−05:00 ET"},
  { state: "Minnesota", abv: "MN" ,offset:-6,offTime:"UTC−06:00 CT"},
  { state: "Missouri", abv: "MO" ,offset:-6,offTime:"UTC−06:00 CT"},
  { state: "Mississippi", abv: "MS" ,offset:-6,offTime:"UTC−06:00 CT"},
  { state: "Montana", abv: "MT" ,offset:-7,offTime:"UTC−07:00 MT"},
  { state: "Nebraska", abv: "NE" ,offset:-6,offTime:"UTC−06:00 CT"},
  { state: "Nevada", abv: "NV" ,offset:-7,offTime:"UTC−07:00 MT"},
  { state: "New Hampshire", abv: "NH" ,offset:-5,offTime:"UTC−05:00 ET"},
  { state: "New Jersey", abv: "NJ" ,offset:-5,offTime:"UTC−05:00 ET"},
  { state: "New Mexico", abv: "NM" ,offset:-7,offTime:"UTC−07:00 MT"},
  { state: "New York", abv: "NY" ,offset:-5,offTime:"UTC−05:00 ET"},
  { state: "North Carolina", abv: "NC" ,offset:-5,offTime:"UTC−05:00 ET"},
  { state: "North Dakota", abv: "ND" ,offset:-6,offTime:"UTC−06:00 CT"},
  { state: "Ohio", abv: "OH" ,offset:-5,offTime:"UTC−05:00 ET"},
  { state: "Oklahoma", abv: "OK" ,offset:-6,offTime:"UTC−06:00 CT"},
  { state: "Oregon", abv: "OR" ,offset:-7,offTime:"UTC−07:00 MT"},
  { state: "Pennsylvania", abv: "PA" ,offset:-5,offTime:"UTC−05:00 ET"},
  { state: "Rhode Island", abv: "RI" ,offset:-5,offTime:"UTC−05:00 ET"},
  { state: "South Carolina", abv: "SC" ,offset:-5,offTime:"UTC−05:00 ET"},
  { state: "South Dakota", abv: "SD" ,offset:-6,offTime:"UTC−06:00 CT"},
  { state: "Tennessee", abv: "TN" ,offset:-5,offTime:"UTC−05:00 ET"},
  { state: "Texas", abv: "TX" ,offset:-6,offTime:"UTC−06:00 CT"},
  { state: "Utah", abv: "UT" ,offset:-7,offTime:"UTC−07:00 MT"},
  { state: "Vermont", abv: "VT" ,offset:-5,offTime:"UTC−05:00 ET"},
  { state: "Virginia", abv: "VA" ,offset:-5,offTime:"UTC−05:00 ET"},
  { state: "Washington", abv: "WA" ,offset:-8,offTime:"UTC−08:00 PT"},
  { state: "West Virginia", abv: "WV" ,offset:-5,offTime:"UTC−05:00 ET"},
  { state: "Wisconsin", abv: "WI" ,offset:-6,offTime:"UTC−06:00 CT"},
  { state: "Wyoming", abv: "WY" ,offset:-7,offTime:"UTC−07:00 MT"},
];
